version: "1.1"

services:
  nextjs:
    ports:
      - 4000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/build
